enum VariableType {
    ReservasInternacionales = 1,
    TipoCambioMinorista = 4,
    TipoCambioMayorista = 5,
    TasaPoliticaMonetaria = 6,
    BADLARPesosBancosPrivados = 7,
    TM20PesosBancosPrivados = 8,
    TasasOperacionesPaseActivasBCRA1DiaPlazo = 9,
    TasasOperacionesPasePasivasBCRA1DiaPlazo = 10,
    TasasInteresPrestamosEntidadesFinancierasPrivadasBAIBAR = 11,
    TasasInteresDepositos30DiasPlazoEntidadesFinancieras = 12,
    TasaInteresPrestamosAdelantosCuentaCorriente = 13,
    TasaInteresPrestamosPersonales = 14,
    BaseMonetariaTotalMillonesPesos = 15,
    CirculacionMonetariaMillonesPesos = 16,
    BilletesMonedasPoderPublicoMillonesPesos = 17,
    EfectivoEntidadesFinancierasMillonesPesos = 18,
    DepositosBancosCtaCtePesosBCRA = 19,
    DepositosEfectivoEntidadesFinancierasTotalMillonesPesos = 21,
    DepositosCuentasCorrientesNetoUtilizacionFUCO = 22,
    DepositosCajaAhorrosMillonesPesos = 23,
    DepositosPlazoInversionesExcluyeCEDROSMillonesPesos = 24,
    M2PrivadoPromedioMovil30DiasVariacionInteranual = 25,
    PrestamosEntidadesFinancierasSectorPrivadoMillonesPesos = 26,
    InflacionMensualVariacionPorcentaje = 27,
    InflacionInteranualVariacionPorcentajeIA = 28,
    InflacionEsperadaREMMedianiaVariacionPorcentajeIA = 29,
    CERBase220021 = 30,
    UnidadValorAdquisitivoUVAPesosBase313201601405 = 31,
    UnidadViviendaUVIPesosBase313201601405 = 32,
    TasaPoliticaMonetariaEAPorcentaje = 34,
    BADLARPesosBancosPrivadosEAPorcentaje = 35,
    IndiceContratosLocacionICLLey27551Base306201 = 40,
    TasasOperacionesPasePasivasBCRA1DiaPlazoEAPorcentaje = 41,
  }
  
  export default VariableType;
  